name: Generating API Config JSON

on:
  push:
    paths:
    - 'config/v3/**'

jobs:
  generate_api_json:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install of dependencies including directory-tree
        run: npm ci
      - name: Generate JSON file with Javascript
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const dirTree = require("directory-tree");
            const tree = dirTree('./config/v3', {extensions:/\.json$/});
            fs.writeFile('./api-data/config-tree.json', JSON.stringify(tree, null, 2), function (err) {
                if (err) throw err;
                console.log('Saved!');
            });
      - name: Commit terminology
        run: |
          git add api-data/config-tree.json
          git commit api-data/config-tree.json -m "Config tree json file updated"
          git push
          
