name: Deriv App ID Generator

on:
    issue_comment:
        types: [edited]

jobs:
    generate_app_id:
        runs-on: ubuntu-latest
        steps:
            - name: Capture Vercel preview URL
              id: vercel_preview_url
              uses: binary-com/vercel-preview-url-action@v1.0.5
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Generate Deriv App ID for deployment Preview URL
              uses: binary-com/deriv-app-id-action@v1
              with:
                  DERIV_API_TOKEN: ${{ secrets.DERIV_API_TOKEN }}
                  DERIV_APP_ID: ${{ secrets.DERIV_APP_ID }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  vercel_preview_url: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}     
            - name: Comment on pull request with App ID and URLs
              uses: marocchino/sticky-pull-request-comment@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{github.event.issue.number}}
                  header: deriv-app-id-action
                  message: |
                      A production App ID was automatically generated for this PR. ([log](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}))
                      - **PR**: [${{ steps.generate_app_id.outputs.pr_url }}](${{ steps.generate_app_id.outputs.pr_url }})
                      - **URL**: [${{ steps.vercel_preview_url.outputs.vercel_preview_url }}](${{ steps.vercel_preview_url.outputs.vercel_preview_url }})
                      - **App ID**: `${{ steps.generate_app_id.outputs.app_id }}`
              
                      <details>
                        <summary>Click here to copy & paste above information.</summary>

                        ```
                        - **PR**: [${{ steps.generate_app_id.outputs }}](${{ steps.generate_app_id.outputs }})
                        - **URLs**:
                            - **w/ App ID + Server**: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}?server_url=frontend.binaryws.com&app_id=${{ steps.generate_app_id.outputs.app_id }}
                            - **Original**: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
                        - **App ID**: `${{ steps.generate_app_id.outputs.app_id }}`
                        ```
                      </details>
                      
            - name: Store generated URL in artifact
              run: echo "HOME_URL=${{ steps.vercel_preview_url.outputs.vercel_preview_url }}?server_url=frontend.binaryws.com&app_id=${{ steps.generate_app_id.outputs.app_id }}" >> ${{ github.workspace }}/url.txt
            - name: Upload artifact
              uses: actions/upload-artifact@master
              with:
                  name: generated_url
                  path: ${{ github.workspace }}/url.txt
                  retention-days: 1
